### ISSUE TITLE
Can I install this on a Raspberry Pi?

### ISSUE THREAD

**Issue by phoenixg** [maxyermayank/docker-compose-elasticsearch-kibana#13]
model 3B

**Comment by ecklf** [comment]
可以

**Comment by maxyermayank** [comment]
@phoenixg Issue doesn't related to this repository as you are looking to run on Raspberry PI. Here is the article to install Docker on Raspberry PI https://howchoo.com/g/nmrlzmq1ymn/how-to-install-docker-on-your-raspberry-pi. Also, ELK stack images are large and requires quite a bit resources so it won't be efficient at all.
