### ISSUE TITLE
Cannot replicate configuration

### ISSUE THREAD

**Issue by sbabicz** [maxyermayank/docker-compose-elasticsearch-kibana#15]
docker-compose up
WARNING: Some services (elasticsearch, elasticsearch2, elasticsearch3) use the 'deploy' key, which will be ignored. Compose does not support 'deploy' configuration - use `docker stack deploy` to deploy to a swarm.
Recreating elasticsearch3 ...
Recreating elasticsearch1 ... error
Recreating elasticsearch3 ... done

Recreating elasticsearch2 ... done

ERROR: for elasticsearch  Cannot start service elasticsearch: driver failed programming external connectivity on endpoint elasticsearch1 (7a8316d99ac2763f4ca5e44c79ce1f8e5d76704d4941d224dd7bc8396b0306a1): Error starting userland proxy: listen tcp 0.0.0.0:9300: bind: address already in use
ERROR: Encountered errors while bringing up the project.

**Comment by rong0312** [comment]
you are using docker-compose commands, please try to use 'docker stack deploy' (look for the docs)

**Comment by sbabicz** [comment]
Managed to get it working! Thanks a lot for the config!
