### ISSUE TITLE
elasticsearch killed automaticaly after starting kibana

### ISSUE THREAD

**Issue by mahboubehShiri1999** [maxyermayank/docker-compose-elasticsearch-kibana#17]
i am new to elk and kibana and recently installed kibana version 6.4.3 and elasticsearch version 6.4.3 on centos7 and my jdk version is 1.8.0_212 .i started elasticsearch with the command"bin/elasticsearch" and kibana with "bin/kibana" .both of them start correctly but when i wrote "http://localhost:6501" on my browser elasticsearch killed.

**Comment by Ash2440** [comment]
Because you are running both on low memory(RAM). You have to increase RAM at least 4GB is required to only run and check and to work on that constantly you need more than 8 GB. I have solved this same issue.

**Comment by aatifnazar26** [comment]
@Ash2440 I have 2GB RAM and I can see that 1049 MB is available. But whenever I start both, elasticsearch gets killed and I can see that Kibana killed it. Can this be avoided without increasing RAM?

**Comment by Ash2440** [comment]
@aatifnazar26 Sorry I did mistake in writing before so I have changed my previous comment. In my mind was, you need at least 2GB of RAM only for this elastic search and rest of RAM is also needed for OS and other services. So it's mean on 4GB system it can run and you can check but your system might be very slow.
