### ISSUE TITLE
Version in "./docker-compose.yml" is unsupported

### ISSUE THREAD

**Issue by louiscoetzee** [maxyermayank/docker-compose-elasticsearch-kibana#18]
Hi, i installed docker-compose version 1.23 as indicated in the docs. Cloned the repo and I get the following error. Any suggestions please?

ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

I am brand new to docker and docker-compose world.

**Comment by wub** [comment]
Try changing version to 3.3 in `docker-compose.yml`

**Comment by stgrmks** [comment]
3.6 should work
