### ISSUE TITLE
Ping TImeout

### ISSUE THREAD

**Issue by whoisstan** [maxyermayank/docker-compose-elasticsearch-kibana#2]
Thanks for providing the docker-compose file. I am struggling with an issue that I believe is related to timeouts:

clock_1     | Elasticsearch WARNING: 2018-10-14T13:42:54Z
clock_1     |   Unable to revive connection: http://localhost:9200/

I am seeing this when I use the ES npm modue and I believe it's a timeout issue

https://github.com/elastic/elasticsearch-js/issues/142#issuecomment-73555987

Is there an environment variable to adjust that through docker-compose, I am not an ES expert and just starting to use it, hence my question. Thank you.

**Comment by jonathanmv** [comment]
I also facing the same issue. I cloned the repository and ran `docker-compose up -d` and then tried to `curl localhost`.

For few seconds I got `curl: (52) Empty reply from server` and then started to get `curl: (7) Failed to connect to localhost port 9200: Connection refused` when running `curl http://localhost:9200/_nodes?pretty=true`. And Kibana also says `Unable to connect to Elasticsearch at http://elasticsearch:9200.`

Does it happen the same to you @maxyermayank?
Did you get to find a work around @whoisstan?

**Comment by tp** [comment]
Ah, it seems like this is the same as #1, no?

**Comment by tp** [comment]
If someone here is just looking for a simple, single-node ES + Kibana, this worked for me:

```
docker run -p 5601:5601 -p 9200:9200 -p 5044:5044 -it --name elk sebp/elk
```

Would like to get back to the cluster setup soon, but for now I just need some version for evaluation.

**Comment by tigermax139** [comment]
sudo sysctl -w vm.max_map_count=262144

**Comment by ambigus9** [comment]
> sudo sysctl -w vm.max_map_count=262144

This solve memory issues. If you need, you can check logs:

`docker-compose logs elasticsearch`
