### ISSUE TITLE
Error "Minimum memory limit can not be less than memory reservation limit" occurs.

### ISSUE THREAD

**Issue by ch-saeki** [maxyermayank/docker-compose-elasticsearch-kibana#22]
When I clone this repository and run it, I get an error `Minimum memory limit can not be less than memory reservation limit`, so I fixed it by changing the memory limit of elasticsearch1 from 256M to 1G and it solved the problem. Should I make it a pull request?

my env
```
Docker version 20.10.7, build 20.10.7-0ubuntu5~20.04.2
docker-compose version 1.29.2, build 5becea4c
```

**Comment by withchristopher** [comment]
I also have the same error message.
```
or elasticsearch1  Cannot create container for service elasticsearch: Minimum memory limit can not be less than memory reservation limit, see usage
```
