### ISSUE TITLE
What does the SERVER_NAME: localhost mean?

### ISSUE THREAD

**Issue by Celthi** [maxyermayank/docker-compose-elasticsearch-kibana#3]
I'm a newbie for docker, could you help me understand that what's meaning of the SERVER_NAME: localhost. 
Why we need a SERVER_NAME?
And why it is set to localhost?

**Comment by CannibalKush** [comment]
Those are environment variables, setting Kibana's variables. 

More info here, just ctrl-f "server.name": https://www.elastic.co/guide/en/kibana/current/settings.html

**Comment by Celthi** [comment]
@CannibalKush 

Thanks for the reply. Sorry I see this message after a long time.
The link says that:
> Default: "your-hostname" A human-readable display name that identifies this Kibana instance.

My next question is:
There is a container name that tell other services to find it.
So this name identifies this Kibana among what kind of entities?
